"""File Agent — file search, read, create, modify, organize."""
from __future__ import annotations

import os
from pathlib import Path
from typing import Any

from .base_agent import BaseAgent
from ..runtime.schemas import Observation, PlanStep, StepResult, TaskContext, ModelRole


class FileAgent(BaseAgent):
    name = "file"
    description = "File search, read, create, modify, organize, and convert"
    capabilities = [
        "file_read", "file_write", "file_search", "file_organize",
        "file_create", "file_delete", "file_convert",
    ]
    tools: list[str] = []

    async def execute(self, step: PlanStep, context: TaskContext) -> StepResult:
        observations: list[Observation] = []
        title_lower = step.title.lower()
        desc_lower = step.description.lower()

        # Determine action from step
        if any(w in title_lower + desc_lower for w in ["read", "open", "view", "content"]):
            return await self._read_file(step, context, observations)
        elif any(w in title_lower + desc_lower for w in ["create", "write", "save"]):
            return await self._create_file(step, context, observations)
        elif any(w in title_lower + desc_lower for w in ["search", "find", "locate"]):
            return await self._search_files(step, context, observations)
        elif any(w in title_lower + desc_lower for w in ["list", "directory", "folder"]):
            return await self._list_directory(step, context, observations)
        else:
            return await self._general_file_op(step, context, observations)

    async def _read_file(self, step: PlanStep, context: TaskContext, obs: list) -> StepResult:
        """Read a file's contents."""
        # Extract path from step description
        path = self._extract_path(step.description or step.title)
        if not path:
            return StepResult(success=False, message="No file path specified")

        try:
            p = Path(path)
            if not p.exists():
                return StepResult(success=False, message=f"File not found: {path}")

            content = p.read_text(encoding="utf-8", errors="replace")[:50000]
            obs.append(self._make_observation(
                "filesystem", f"Read file: {p.name} ({len(content)} chars)",
                data={"path": str(p), "size": p.stat().st_size},
                step_id=step.step_id,
            ))

            return StepResult(
                success=True,
                message=f"Read {p.name} ({len(content)} characters)",
                data={"path": str(p), "content": content, "size": p.stat().st_size},
                observations=obs,
                needs_verification=False,
            )
        except Exception as exc:
            return StepResult(success=False, message=f"Failed to read file: {exc}")

    async def _create_file(self, step: PlanStep, context: TaskContext, obs: list) -> StepResult:
        """Create or write a file."""
        path = self._extract_path(step.description or step.title)
        if not path:
            return StepResult(success=False, message="No file path specified")

        # Get content from previous results or generate via LLM
        content = ""
        for prev in context.previous_results.values():
            if "content" in prev.get("data", {}):
                content = prev["data"]["content"]
                break
            if "response" in prev.get("data", {}):
                content = prev["data"]["response"]
                break
            if "summary" in prev.get("data", {}):
                content = prev["data"]["summary"]
                break

        if not content:
            try:
                content = await self._call_llm(
                    messages=[
                        {"role": "system", "content": "Generate the requested file content."},
                        {"role": "user", "content": f"Create content for: {step.description or step.title}"},
                    ],
                    role=ModelRole.FAST,
                )
            except Exception:
                content = f"# {step.title}\n\nGenerated by Genie"

        try:
            p = Path(path)
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(content, encoding="utf-8")

            obs.append(self._make_observation(
                "filesystem", f"Created file: {p.name} ({len(content)} chars)",
                data={"path": str(p), "size": len(content)},
                step_id=step.step_id,
            ))

            return StepResult(
                success=True,
                message=f"Created {p.name} ({len(content)} characters)",
                data={"path": str(p), "size": len(content)},
                observations=obs,
                artifacts=[str(p)],
            )
        except Exception as exc:
            return StepResult(success=False, message=f"Failed to create file: {exc}")

    async def _search_files(self, step: PlanStep, context: TaskContext, obs: list) -> StepResult:
        """Search for files matching a pattern."""
        import glob
        query = step.description or step.title
        search_dir = self._extract_path(query) or os.path.expanduser("~")

        try:
            pattern = "**/*"
            results = list(Path(search_dir).glob(pattern))[:100]
            files = [{"path": str(f), "name": f.name, "is_dir": f.is_dir()} for f in results[:50]]

            return StepResult(
                success=True,
                message=f"Found {len(results)} items in {search_dir}",
                data={"results": files, "total": len(results)},
                observations=obs,
                needs_verification=False,
            )
        except Exception as exc:
            return StepResult(success=False, message=f"File search failed: {exc}")

    async def _list_directory(self, step: PlanStep, context: TaskContext, obs: list) -> StepResult:
        """List contents of a directory."""
        path = self._extract_path(step.description or step.title) or os.getcwd()

        try:
            p = Path(path)
            if not p.exists():
                return StepResult(success=False, message=f"Directory not found: {path}")

            entries = []
            for item in sorted(p.iterdir()):
                entries.append({
                    "name": item.name,
                    "is_dir": item.is_dir(),
                    "size": item.stat().st_size if item.is_file() else None,
                })

            return StepResult(
                success=True,
                message=f"Directory {p.name}: {len(entries)} items",
                data={"path": str(p), "entries": entries[:100]},
                observations=obs,
                needs_verification=False,
            )
        except Exception as exc:
            return StepResult(success=False, message=f"Directory listing failed: {exc}")

    async def _general_file_op(self, step: PlanStep, context: TaskContext, obs: list) -> StepResult:
        """Handle general file operations via LLM reasoning."""
        response = await self._call_llm(
            messages=[
                {"role": "system", "content": "You are a file management assistant. Describe what file operations are needed."},
                {"role": "user", "content": f"Task: {step.title}\nDetails: {step.description}"},
            ],
            role=ModelRole.FAST,
        )
        return StepResult(
            success=True,
            message=response[:500],
            data={"response": response},
            observations=obs,
            needs_verification=False,
        )

    @staticmethod
    def _extract_path(text: str) -> str | None:
        """Try to extract a file path from text."""
        import re
        patterns = [
            r'[A-Za-z]:\\[^\s"\'<>|]+',  # Windows absolute
            r'/[^\s"\'<>|]+',              # Unix absolute
            r'[^\s"\'<>|]+\.[a-zA-Z]{1,5}',  # filename.ext
        ]
        for pattern in patterns:
            match = re.search(pattern, text)
            if match:
                return match.group(0)
        return None
